---

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




```{r echo=FALSE}
library(grid)
library(gridExtra)
library(png)

# Establecer información de identificación del equipo y del proyecto
equipo <- "Marco Antonio Obregón Flores"
evaluacion <- "Reporte estadístico de resultados"
posgrado <- "Maestría en Ciencia de Datos"
unidad_aprendizaje <- "Métodos Estádisticos Multivariados"
profesor <- "Rosa Isela Hernandez Zamora"
fecha_entrega <- "28 de marzo de 2023"

# Cargar logos de la UANL y la FCFM
logo_uanl <- rasterGrob(readPNG("logo_uanl.png"), interpolate=TRUE)
logo_fcfm <- rasterGrob(readPNG("logo_fcfm.png"), interpolate=TRUE)

# Crear la portada
grid.arrange(
  # Logos y título
  arrangeGrob(
    logo_uanl, logo_fcfm,
    top = "Universidad Autónoma de Nuevo León\nFacultad de Ciencias Físicas y Matemáticas",
    bottom = "Proyecto de la Unidad de Aprendizaje: Métodos Estádisticos Multivariados",
    heights = c(1, 1)
  ),
  # Información de identificación del equipo y del proyecto
  arrangeGrob(
    textGrob("Datos de identificación del equipo:", gp = gpar(fontsize = 14, fontface = "bold")),
    textGrob(paste("Equipo:", equipo)),
    textGrob(paste("Número de evaluación:", evaluacion)),
    textGrob(paste("Posgrado:", posgrado)),
    textGrob(paste("Unidad de aprendizaje:", unidad_aprendizaje)),
    textGrob(paste("Profesor:", profesor)),
    textGrob(paste("Fecha de entrega:", fecha_entrega)),
    ncol = 1,
    widths = 1
  ),
  nrow = 2,
  heights = c(2, 1)
)


```


